// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY
export const notes = [
  {
    "id": "2exlma",
    "body": "this is a test",
    "indent": 0
  },
  {
    "id": "m3o6zt",
    "body": "here are some links:",
    "indent": 1
  },
  {
    "id": "ztj9ai",
    "body": "https://www.marathondesgrandscrus.com",
    "indent": 2
  },
  {
    "id": "i9na6h",
    "body": "[Marathon des grands crus 17/10/2021 à Dijon](https://www.youtube.com/watch?v=qQCA4KLtdog)",
    "indent": 2
  },
  {
    "id": "0brnov",
    "body": "course à pied",
    "indent": 2
  },
  {
    "id": "3b9f5u",
    "body": "https://www.openrunner.com/route-details/23448723",
    "indent": 3
  },
  {
    "id": "fw58d5",
    "body": "Bad Schandau",
    "indent": 0
  },
  {
    "id": "ghz055",
    "body": "perhaps they have Airbnbs there? :thinking:",
    "indent": 1
  },
  {
    "id": "9mqmsg",
    "body": "basic info: https://de.wikipedia.org/wiki/Bad_Schandau",
    "indent": 1
  },
  {
    "id": "27e5wu",
    "body": "looks like a nice little town",
    "indent": 1,
    "image": "badsch.jpg"
  },
  {
    "id": "xgc6qx",
    "body": "Icon Examples",
    "indent": 0
  },
  {
    "id": "yduf9z",
    "body": "stareyes :stareyes: and text after it",
    "indent": 1
  },
  {
    "id": "d7chx6",
    "body": "smile :smile:",
    "indent": 1
  },
  {
    "id": "1n4464",
    "body": "ohmygod :ohmygod:",
    "indent": 1
  },
  {
    "id": "dqmip1",
    "body": "whatever :whatever:",
    "indent": 1
  },
  {
    "id": "6vsp8o",
    "body": "shootingstar :shootingstar:",
    "indent": 1
  },
  {
    "id": "b099b2",
    "body": "muscle :muscle:",
    "indent": 1
  },
  {
    "id": "jjavjv",
    "body": "thumbsup :thumbsup:",
    "indent": 1
  },
  {
    "id": "v7k1i5",
    "body": "twohearts :twohearts:",
    "indent": 1
  },
  {
    "id": "4bd6az",
    "body": "redheart :redheart:",
    "indent": 1
  },
  {
    "id": "840nxa",
    "body": "water :water:",
    "indent": 1
  },
  {
    "id": "y2580i",
    "body": "twinkle :twinkle:",
    "indent": 1
  },
  {
    "id": "oee1hn",
    "body": "laugh :laugh:",
    "indent": 1
  },
  {
    "id": "avvhls",
    "body": "check :check:",
    "indent": 1
  },
  {
    "id": "gah6mv",
    "body": "ohno :ohno:",
    "indent": 1
  },
  {
    "id": "7rxb1x",
    "body": "party :party:",
    "indent": 1
  }
];
