import fs from "node:fs";
import path from "node:path";

export interface OutlineItem {
  id: string;
  body: string;
  indent: number;
  image?: string;
}

export interface ParseOutlineOptions {
  inputRelativePath: string;
  outputRelativePath: string;
  exportVarName?: string;
  imagesRelativeDir?: string;
}

function generateSuuid(): string {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  let result = "";
  for (let i = 0; i < 6; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

export function parseOutlineFile(options: ParseOutlineOptions): OutlineItem[] {
  const {
    inputRelativePath,
    outputRelativePath,
    exportVarName = "notes",
    imagesRelativeDir = "images/outline"
  } = options;

  const inputFilePath = path.resolve(inputRelativePath);
  const outputFilePath = path.resolve(outputRelativePath);
  const outputDir = path.dirname(outputFilePath);

  if (!fs.existsSync(inputFilePath)) {
    console.warn(`[outline-parser] Input file not found: ${inputFilePath}`);
    return [];
  }

  const fileContent = fs.readFileSync(inputFilePath, "utf-8");
  const lines = fileContent.split(/\r?\n/);
  const items: OutlineItem[] = [];

  const imagesDir = path.resolve(imagesRelativeDir);
  const availableImages = fs.existsSync(imagesDir) ? fs.readdirSync(imagesDir) : [];

  for (const line of lines) {
    if (!line.trim()) {
      continue;
    }

    // Calculate indent count (leading tabs)
    let indent = 0;
    while (indent < line.length && line.charAt(indent) === "\t") {
      indent++;
    }

    // Strip leading tabs
    let content = line.substring(indent);

    // Strip "- " or "-" prefix
    if (content.startsWith("- ")) {
      content = content.substring(2);
    } else if (content.startsWith("-")) {
      content = content.substring(1);
    }

    let image = "";
    const tagMatch = content.match(/##([a-zA-Z0-9_\-]+)\s*$/);
    if (tagMatch) {
      const tag = tagMatch[1];
      // Remove tag from content
      content = content.replace(/##[a-zA-Z0-9_\-]+\s*$/, "").trimEnd();

      // Look for matching file in images directory
      const matchedFile = availableImages.find((f) => {
        const ext = path.extname(f).toLowerCase();
        const base = path.basename(f, path.extname(f)).toLowerCase();
        return (
          base === tag.toLowerCase() &&
          [".jpg", ".jpeg", ".png", ".gif", ".webp"].includes(ext)
        );
      });

      if (matchedFile) {
        image = matchedFile;
      } else {
        image = `NOT_FOUND:${tag}`;
      }
    }

    const id = generateSuuid();
    const item: OutlineItem = {
      id,
      body: content,
      indent
    };

    if (image) {
      item.image = image;
    }

    items.push(item);
  }

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const jsContent = `// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY\nexport const ${exportVarName} = ${JSON.stringify(
    items,
    null,
    2
  )};\n`;

  fs.writeFileSync(outputFilePath, jsContent, "utf-8");
  console.log(`[outline-parser] Parsed ${items.length} items from ${inputRelativePath} -> ${outputRelativePath}`);

  return items;
}
