import fs from "node:fs";
import path from "node:path";

export interface LinkItem {
  url: string;
  title: string;
}

export function parseSeeAlsoLinks(): void {
  const inputFilePath = path.resolve("data", "see-also-links.dpod.txt");
  const outputDir = path.resolve("js", "data");
  const outputFilePath = path.join(outputDir, "see-also-links.js");

  if (!fs.existsSync(inputFilePath)) {
    console.warn(`[parse-see-also-links] Input file not found: ${inputFilePath}`);
    return;
  }

  const fileContent = fs.readFileSync(inputFilePath, "utf-8");
  const lines = fileContent.split(/\r?\n/);

  const links: LinkItem[] = [];

  for (const line of lines) {
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.startsWith("#")) {
      continue;
    }

    const separatorIndex = trimmedLine.indexOf(";");
    if (separatorIndex === -1) {
      continue;
    }

    const url = trimmedLine.slice(0, separatorIndex).trim();
    const title = trimmedLine.slice(separatorIndex + 1).trim();

    if (url && title) {
      links.push({ url, title });
    }
  }

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const jsContent = `// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY\nexport const seeAlsoLinks = ${JSON.stringify(
    links,
    null,
    2
  )};\n`;

  fs.writeFileSync(outputFilePath, jsContent, "utf-8");
  console.log(`[parse-see-also-links] Parsed ${links.length} links -> ${outputFilePath}`);
}
